// flow-typed signature: 06fd663834ae3eda04865664f14a50df
// flow-typed version: <<STUB>>/random-material-color_v1.0.3/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'random-material-color'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'random-material-color' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'random-material-color/dist/randomColor' {
  declare module.exports: any;
}

declare module 'random-material-color/gulpfile' {
  declare module.exports: any;
}

declare module 'random-material-color/src/defaultPalette' {
  declare module.exports: any;
}

declare module 'random-material-color/src/randomColor' {
  declare module.exports: any;
}

// Filename aliases
declare module 'random-material-color/dist/randomColor.js' {
  declare module.exports: $Exports<'random-material-color/dist/randomColor'>;
}
declare module 'random-material-color/gulpfile.js' {
  declare module.exports: $Exports<'random-material-color/gulpfile'>;
}
declare module 'random-material-color/src/defaultPalette.js' {
  declare module.exports: $Exports<'random-material-color/src/defaultPalette'>;
}
declare module 'random-material-color/src/randomColor.js' {
  declare module.exports: $Exports<'random-material-color/src/randomColor'>;
}
