// flow-typed signature: dbabd3f7ad812a964240ef2621f059e3
// flow-typed version: <<STUB>>/react-photo-gallery_v7.0.2/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-photo-gallery'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-photo-gallery' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-photo-gallery/dist/react-photo-gallery.esm' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/dist/react-photo-gallery.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-photo-gallery/dist/react-photo-gallery.esm.js' {
  declare module.exports: $Exports<'react-photo-gallery/dist/react-photo-gallery.esm'>;
}
declare module 'react-photo-gallery/dist/react-photo-gallery.umd.js' {
  declare module.exports: $Exports<'react-photo-gallery/dist/react-photo-gallery.umd'>;
}
